import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import vm from 'node:vm';
const source=await readFile(new URL('../web/app.js',import.meta.url),'utf8');
const helpers=source.slice(source.indexOf('const tripCovers='),source.indexOf('const active='));
const calendar=source.slice(source.indexOf('async function publicCalendar(){'),source.indexOf("$('publicPrev').onclick"));
async function render(items){const elements={publicWeek:{},publicAgenda:{},date:{value:''},vehicle:{value:''}};const scope={$:id=>elements[id],api:async()=>({items}),publicWeek:'2026-10-05',calendarGeneration:0,day:s=>s.split('-').reverse().join('/'),esc:s=>String(s),todayISO:()=> '2026-10-07',shift:(s,n)=>new Date(Date.parse(s+'T12:00Z')+n*86400000).toISOString().slice(0,10)};await vm.runInNewContext(helpers+calendar+';publicCalendar()',scope);return [...elements.publicAgenda.innerHTML.matchAll(/<td\b[^>]*>[\s\S]*?<\/td>/g)].map(x=>x[0]);}
test('Calendário público mostra todos os dias da reserva e respeita a devolução',async()=>{const cells=await render([{date:'2026-10-08',returnDate:'2026-10-09',vehicle:'Iveco',start:'08:00',end:'17:00',allDay:true,status:'Programado'}]);assert.match(cells[4],/DIA INTEIRO/);assert.match(cells[4],/disabled/);assert.match(cells[4],/Dia reservado/);assert.match(cells[5],/Sem programação/);});
test('Reserva parcial começa antes da semana: sexta intermediária inteira e sábado devolução',async()=>{const cells=await render([{date:'2026-10-02',returnDate:'2026-10-10',vehicle:'Saveiro',start:'16:00',end:'09:00',allDay:false,status:'Programado'}]);assert.match(cells[11],/DIA INTEIRO/);assert.match(cells[11],/Dia reservado/);assert.match(cells[12],/Devolução 09:00/);assert.match(cells[12],/Solicitar este dia/);assert.match(cells[13],/Sem programação/);});

test('Calendário dos usuários exibe destino e destaca urgência',async()=>{const cells=await render([{date:'2026-10-09',vehicle:'Iveco',start:'08:00',end:'10:00',destination:'Obra em Osasco',urgency:'urgent',status:'Programado'}]);assert.match(cells[4],/Obra em Osasco/);assert.match(cells[4],/urgent-badge/);assert.match(cells[4],/URGENTE/);assert.doesNotMatch(cells[3],/URGENTE/);});
