CREATE TABLE IF NOT EXISTS requests (
 id TEXT PRIMARY KEY, status TEXT NOT NULL, date TEXT NOT NULL DEFAULT '',
 start TEXT NOT NULL DEFAULT '', end TEXT NOT NULL DEFAULT '', vehicle TEXT NOT NULL,
 driver_key TEXT NOT NULL DEFAULT '', payload TEXT NOT NULL,
 version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS requests_schedule ON requests(date, status, vehicle);
CREATE TABLE IF NOT EXISTS sessions (hash TEXT PRIMARY KEY, expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS limits (bucket TEXT PRIMARY KEY, count INTEGER NOT NULL, expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS audit (id INTEGER PRIMARY KEY AUTOINCREMENT, request_id TEXT, action TEXT NOT NULL, created_at TEXT NOT NULL);
