import {digest,verifyPassword} from './auth.mjs';
import {accountRoutes,currentUser,decisionNotification,adminAccounts} from './accounts.mjs';
const norm=s=>String(s||'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ');
const now=()=>new Date().toISOString();
class Problem extends Error{constructor(status,message,extra={}){super(message);this.status=status;this.extra=extra}}
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}});
async function body(req){if(Number(req.headers.get('Content-Length'))>1000000)throw new Problem(413,'Dados muito grandes.');const text=await req.text();if(text.length>1000000)throw new Problem(413,'Dados muito grandes.');try{return JSON.parse(text)}catch{throw new Problem(400,'Dados inválidos.')}}
function text(value,label,max=250){if(typeof value!=='string'||!value.trim()||value.length>max)throw new Problem(400,`Preencha ${label}.`);return value.trim()}
export function validate(raw,{publicForm=false}={}){
 const d={};d.vehicle=text(raw.vehicle,'o veículo');if(!['Iveco','Saveiro'].includes(d.vehicle))throw new Problem(400,'Veículo inválido.');
 d.date=text(raw.date,'a data');if(!/^\d{4}-\d{2}-\d{2}$/.test(d.date)||isNaN(Date.parse(d.date+'T12:00:00Z'))||new Date(d.date+'T12:00:00Z').toISOString().slice(0,10)!==d.date)throw new Problem(400,'Data inválida.');
 d.returnDate=raw.returnDate||d.date;if(!/^\d{4}-\d{2}-\d{2}$/.test(d.returnDate)||isNaN(Date.parse(d.returnDate+'T12:00:00Z'))||new Date(d.returnDate+'T12:00:00Z').toISOString().slice(0,10)!==d.returnDate||d.returnDate<d.date)throw new Problem(400,'A devolução deve ser uma data válida igual ou posterior à retirada.');
 d.allDay=!publicForm&&(raw.allDay===true||raw.allDay==='true');
 if(publicForm){d.start='';d.end='';}else{for(const field of ['start','end']){d[field]=d.allDay?(field==='start'?'00:00':'23:59'):text(raw[field],'os horários');if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(d[field]))throw new Problem(400,'Horário inválido.');}if(d.returnDate===d.date&&d.end<=d.start)throw new Problem(400,'O retorno deve ser depois da saída.');}
 d.destination=text(raw.destination,'o destino',500);d.purpose=text(raw.purpose,'a finalidade',2500);d.material=raw.material;if(!['yes','no'].includes(d.material))throw new Problem(400,'Informe se levará material para obra.');
 if(publicForm){d.name=text(raw.name,'seu nome',100);d.department=text(raw.department,'seu setor',100);d.email=text(raw.email,'seu e-mail',160);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(d.email))throw new Problem(400,'E-mail inválido.');const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date());if(d.date<today)throw new Problem(400,'Escolha hoje ou uma data futura.');d.driver='';}
 else d.driver=text(raw.driver,'o motorista',100);
 if(publicForm){d.urgency=raw.urgency||'normal';if(!['normal','urgent'].includes(d.urgency))throw new Problem(400,'Escolha uma urgência válida.');d.urgencyReason=d.urgency==='urgent'?text(raw.urgencyReason,'o motivo da urgência',500):'';}
 if(!publicForm&&raw.beneficiaryName!==undefined)d.name=text(raw.beneficiaryName,'o nome de quem usará o veículo',100);if(!publicForm&&raw.beneficiaryUserId!==undefined)d.beneficiaryUserId=String(raw.beneficiaryUserId);d.notes=typeof raw.notes==='string'?raw.notes.slice(0,2000):'';return d;
}
async function limit(env,key,max,seconds){const bucket=await digest(key),expiry=Date.now()+seconds*1000;await env.DB.prepare('DELETE FROM limits WHERE expires_at < ?').bind(Date.now()).run();const row=await env.DB.prepare('INSERT INTO limits(bucket,count,expires_at) VALUES (?,1,?) ON CONFLICT(bucket) DO UPDATE SET count=count+1 RETURNING count').bind(bucket,expiry).first();if(row.count>max)throw new Problem(429,'Muitas tentativas. Aguarde antes de tentar novamente.');}
async function auth(req,env){const bearer=req.headers.get('Authorization')?.replace(/^Bearer /,'');const cookie=req.headers.get('Cookie')?.match(/(?:^|;\s*)frota_session=([^;]+)/)?.[1];const token=bearer||cookie;if(!token)return null;const row=await env.DB.prepare('SELECT hash FROM sessions WHERE hash=? AND expires_at>?').bind(await digest(token),Date.now()).first();return row?token:null}
const cookie=(token,req,clear=false)=>`frota_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${clear?0:43200}${new URL(req.url).protocol==='https:'?'; Secure':''}`;
async function list(env){const result=await env.DB.prepare('SELECT payload,version FROM requests ORDER BY date,start,created_at').all();return result.results.map(x=>({...JSON.parse(x.payload),version:x.version})).filter(x=>!x.deletedAt)}
function conflictSQL(){return `NOT EXISTS (SELECT 1 FROM requests r WHERE r.id<>? AND r.status NOT IN ('Solicitada','Recusada','Cancelada','Concluída') AND (r.vehicle=? OR (r.driver_key<>'' AND r.driver_key=?)) AND (r.date||'T'||COALESCE(NULLIF(r.start,''),'00:00'))<? AND (COALESCE(NULLIF(json_extract(r.payload,'$.returnDate'),''),r.date)||'T'||CASE WHEN json_extract(r.payload,'$.allDay')=1 THEN '24:00' ELSE COALESCE(NULLIF(r.end,''),'23:59') END)>?)`}
async function storeScheduled(env,d,{id,version,old,confirmBoth}){
 if(d.beneficiaryUserId!==undefined){if(d.beneficiaryUserId){const user=await env.DB.prepare('SELECT id,name,email FROM users WHERE id=? AND NOT EXISTS (SELECT 1 FROM deleted_accounts d WHERE d.user_id=users.id)').bind(d.beneficiaryUserId).first();if(!user)throw new Problem(400,'Conta selecionada não encontrada.');d.userId=user.id;d.name=user.name;d.email=user.email;}else{d.userId=null;d.email='';}delete d.beneficiaryUserId;}
 const other=await env.DB.prepare("SELECT payload FROM requests WHERE id<>? AND date<=? AND COALESCE(NULLIF(json_extract(payload,'$.returnDate'),''),date)>=? AND vehicle<>? AND status NOT IN ('Solicitada','Recusada','Cancelada','Concluída')").bind(id,d.returnDate,d.date,d.vehicle).all();
 other.results=norm(d.driver)==='motorista padrao'?other.results.filter(x=>norm(JSON.parse(x.payload).driver)==='motorista padrao'):[];
 if(other.results.length&&!confirmBoth)throw new Problem(409,'Motorista padrão já tem programação no outro veículo neste período. Confirma o uso dos dois carros?',{confirmBoth:true,other:other.results.map(x=>{const r=JSON.parse(x.payload);return {vehicle:r.vehicle,start:r.start,driver:r.driver}})});
 const value={...old,...d,id,status:'Agendada',driverConfirmed:false,nf:false,loaded:false,warnings:[],updatedAt:now()};
 if(other.results.length)value.dualConfirmed=new Date().toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'});else value.dualConfirmed=null;
 const args=[id,d.vehicle,norm(d.driver),d.returnDate+'T'+(d.allDay?'24:00':d.end),d.date+'T'+d.start];let result;
 if(old)result=await env.DB.prepare(`UPDATE requests SET status='Agendada',date=?,start=?,end=?,vehicle=?,driver_key=?,payload=?,version=version+1,updated_at=? WHERE id=? AND version=? AND ${conflictSQL()}`).bind(d.date,d.start,d.end,d.vehicle,norm(d.driver),JSON.stringify(value),now(),id,version,...args).run();
 else{value.createdAt=now();result=await env.DB.prepare(`INSERT INTO requests(id,status,date,start,end,vehicle,driver_key,payload,created_at,updated_at) SELECT ?,'Agendada',?,?,?,?,?,?,?,? WHERE ${conflictSQL()}`).bind(id,d.date,d.start,d.end,d.vehicle,norm(d.driver),JSON.stringify(value),now(),now(),...args).run();}
 if(!result.meta.changes)throw new Problem(409,'Conflito de horário do motorista/veículo ou registro alterado. Atualize a lista e revise.');
 await env.DB.prepare('INSERT INTO audit(request_id,action,created_at) VALUES (?,?,?)').bind(id,'programação salva',now()).run();if(old?.status==='Solicitada'||!old&&value.userId)await decisionNotification(env,value);return {...value,version:old?version+1:1};
}
export async function handle(req,env){const url=new URL(req.url),path=url.pathname;
 try{
 if(!path.startsWith('/api/')){const res=await env.ASSETS.fetch(req);const headers=new Headers(res.headers);headers.set('X-Content-Type-Options','nosniff');headers.set('Referrer-Policy','same-origin');headers.set('Content-Security-Policy',"default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");return new Response(res.body,{status:res.status,headers});}
 if(!env.DB)throw new Problem(503,'Banco de dados não configurado.');
 if(!['GET','HEAD'].includes(req.method)&&req.headers.get('Origin')&&req.headers.get('Origin')!==url.origin)throw new Problem(403,'Origem não permitida.');
 const ip=req.headers.get('CF-Connecting-IP')||'local';
 if(path==='/api/health')return json({ok:true});
 const account=await accountRoutes(req,env,{body,limit,ip});if(account)return account;
 const user=(path==='/api/calendar'||path==='/api/requests'&&req.method==='POST')?await currentUser(req,env):null;
 if(path==='/api/requests'&&req.method==='POST'&&!user)throw new Problem(401,'Entre na sua conta para consultar a agenda e solicitar.');
 if(path==='/api/calendar'&&req.method==='GET'){const start=url.searchParams.get('week');if(!/^\d{4}-\d{2}-\d{2}$/.test(start||'')||isNaN(Date.parse(start)))throw new Problem(400,'Semana inválida.');const end=new Date(start+'T12:00:00Z');end.setUTCDate(end.getUTCDate()+6);const rows=await env.DB.prepare("SELECT date,vehicle,start,end,status,CASE WHEN trim(json_extract(payload,'$.destination'))='Casa ↔ Empresa' THEN 'Uso reservado' ELSE COALESCE(json_extract(payload,'$.destination'),'') END AS destination,CASE WHEN json_extract(payload,'$.urgency')='urgent' THEN 'urgent' ELSE 'normal' END AS urgency,json_extract(payload,'$.allDay') AS allDay,COALESCE(NULLIF(json_extract(payload,'$.returnDate'),''),date) AS returnDate FROM requests WHERE COALESCE(NULLIF(json_extract(payload,'$.returnDate'),''),date)>=? AND date<=? AND vehicle IN ('Iveco','Saveiro') AND status NOT IN ('Solicitada','Recusada','Cancelada') ORDER BY date,start").bind(start,end.toISOString().slice(0,10)).all();return json({items:rows.results.map(x=>({...x,allDay:!!x.allDay,status:x.status==='Importada'?'A confirmar':x.status==='Concluída'?'Concluída':'Programado'}))});}
 if(path==='/api/login'&&req.method==='POST'){await limit(env,'login:'+ip,10,900);if(!env.ADMIN_PASSWORD_HASH)throw new Problem(503,'Senha administrativa não configurada.');const d=await body(req);if(!await verifyPassword(d.password,env.ADMIN_PASSWORD_HASH))throw new Problem(401,'Senha incorreta.');const token=crypto.randomUUID()+crypto.randomUUID();await env.DB.prepare('DELETE FROM sessions WHERE expires_at < ?').bind(Date.now()).run();await env.DB.prepare('INSERT INTO sessions(hash,expires_at) VALUES (?,?)').bind(await digest(token),Date.now()+43200000).run();return json({ok:true,...(req.headers.get('X-Frota-Desktop')==='1'?{token}:{})},200,{'Set-Cookie':cookie(token,req)});}
 if(path==='/api/requests'&&req.method==='POST'){if(env.PUBLIC_SUBMISSIONS==='false')throw new Problem(403,'Solicitações temporariamente fechadas.');await limit(env,'submit:'+ip,30,86400);const d=validate({...await body(req),name:user.name,email:user.email},{publicForm:true}),id='REQ-'+crypto.randomUUID(),value={...d,userId:user.id,id,status:'Solicitada',createdAt:now(),updatedAt:now(),driverConfirmed:false,nf:false,loaded:false};await env.DB.prepare('INSERT INTO requests(id,status,date,start,end,vehicle,payload,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(id,value.status,d.date,d.start,d.end,d.vehicle,JSON.stringify(value),now(),now()).run();return json({id,message:'Solicitação recebida. Aguarda aprovação.'},201);}
 const token=await auth(req,env);if(!token)throw new Problem(401,'Entre na área administrativa.');
 const usersResponse=await adminAccounts(req,env,{body});if(usersResponse)return usersResponse;
 if(path==='/api/me')return json({admin:true});
 if(path==='/api/logout'&&req.method==='POST'){await env.DB.prepare('DELETE FROM sessions WHERE hash=?').bind(await digest(token)).run();return json({ok:true},200,{'Set-Cookie':cookie('',req,true)});}
 if(path==='/api/requests'&&req.method==='GET')return json({items:await list(env)});
 if(path==='/api/trips'&&req.method==='POST'){const b=await body(req),d=validate(b);return json(await storeScheduled(env,d,{id:'F-'+crypto.randomUUID(),confirmBoth:b.confirmBoth===true}),201);}
 if(path==='/api/import'&&req.method==='POST'){const data=await body(req);if(!Array.isArray(data)||data.length>500)throw new Problem(400,'Importação inválida.');const values=data.map(source=>{if(typeof source.id!=='string'||!source.id.startsWith('EXCEL-')||source.id.length>150||typeof source.vehicle!=='string'||source.vehicle.length>100)throw new Problem(400,'Registro da importação inválido.');return {...source,status:'Importada',driverConfirmed:false,nf:false,loaded:false}});let count=0;for(let i=0;i<values.length;i+=8){const chunk=values.slice(i,i+8),args=chunk.flatMap(value=>[value.id,value.status,value.date||'',value.start||'',value.end||'',value.vehicle,norm(value.driver),JSON.stringify(value),now(),now()]);const r=await env.DB.prepare('INSERT OR IGNORE INTO requests(id,status,date,start,end,vehicle,driver_key,payload,created_at,updated_at) VALUES '+chunk.map(()=>'(?,?,?,?,?,?,?,?,?,?)').join(',')).bind(...args).run();count+=r.meta.changes;}return json({imported:count});}
 const match=path.match(/^\/api\/requests\/([^/]+)$/);if(match&&req.method==='PATCH'){const id=decodeURIComponent(match[1]),b=await body(req),row=await env.DB.prepare('SELECT payload,version FROM requests WHERE id=?').bind(id).first();if(!row)throw new Problem(404,'Registro não encontrado.');if(row.version!==b.version)throw new Problem(409,'Registro alterado. Atualize a lista.');const old=JSON.parse(row.payload);if(old.deletedAt)throw new Problem(404,'Programação excluída.');
 if(b.action==='approve'||b.action==='edit'){if(!['Solicitada','Importada','Agendada','Liberada'].includes(old.status))throw new Problem(400,'Esta viagem não pode ser editada nesta etapa.');return json(await storeScheduled(env,validate(b),{id,version:row.version,old,confirmBoth:b.confirmBoth===true}));}
 const v={...old,updatedAt:now()};const allowed=['driver','nf','load','release','depart','finish','reject','cancel','delete'];if(!allowed.includes(b.action))throw new Problem(400,'Ação inválida.');
 if(b.action==='delete'){if(old.status==='Em viagem')throw new Problem(400,'Registre o retorno antes de excluir uma viagem em andamento.');v.status='Cancelada';v.deletedAt=now();}
 if(b.action==='reject'){if(old.status!=='Solicitada')throw new Problem(400,'Somente solicitações podem ser recusadas.');v.status='Recusada';}
 if(b.action==='cancel'){if(!['Solicitada','Importada','Agendada','Liberada'].includes(old.status))throw new Problem(400,'Não é possível cancelar nesta etapa.');v.status='Cancelada';}
 if(['driver','nf','load','release'].includes(b.action)){if(old.status!=='Agendada')throw new Problem(400,'Primeiro revise e programe a viagem.');if(b.action==='driver')v.driverConfirmed=!v.driverConfirmed;if(b.action==='nf'){if(v.material!=='yes')throw new Problem(400,'Viagem sem carga para obra.');v.nf=!v.nf;if(!v.nf)v.loaded=false;}if(b.action==='load'){if(!v.nf)throw new Problem(400,'Confira a NF antes da carga.');v.loaded=!v.loaded;}if(b.action==='release'){if(!v.driverConfirmed||(v.material==='yes'&&(!v.nf||!v.loaded)))throw new Problem(400,'Confirme motorista, NF e carga antes da saída.');v.status='Liberada';}}
 if(b.action==='depart'){if(old.status!=='Liberada')throw new Problem(400,'A viagem precisa estar liberada.');v.status='Em viagem';v.departedAt=now();}
 if(b.action==='finish'){if(old.status!=='Em viagem')throw new Problem(400,'A viagem precisa estar em andamento.');v.status='Concluída';v.returnedAt=now();}
 const r=await env.DB.prepare('UPDATE requests SET status=?,payload=?,version=version+1,updated_at=? WHERE id=? AND version=?').bind(v.status,JSON.stringify(v),now(),id,b.version).run();if(!r.meta.changes)throw new Problem(409,'Registro alterado. Atualize a lista.');await env.DB.prepare('INSERT INTO audit(request_id,action,created_at) VALUES (?,?,?)').bind(id,b.action,now()).run();if(b.action==='reject'||b.action==='cancel'||b.action==='delete')await decisionNotification(env,v);return json({...v,version:b.version+1});}
 throw new Problem(404,'Rota não encontrada.');
 }catch(error){if(error instanceof Problem)return json({error:error.message,...error.extra},error.status);console.error('API error',error.name,error.message);return json({error:'Não foi possível concluir. Tente novamente.'},500)}
}
