'use strict';
window.frotaAccount={user:null,refresh:()=>{},init,poll};
const accountElement=id=>document.getElementById(id);
let registration=false,pollBusy=false,pendingNotices=[];
const safeText=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function accountApi(path,method='GET',data){const response=await fetch('/api/account/'+path,{method,credentials:'same-origin',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(20000)});const result=await response.json();if(!response.ok){const error=new Error(result.error||'Falha na conexão.');error.status=response.status;throw error}return result;}
async function init(){try{const result=await accountApi('me');window.frotaAccount.user=result.user;window.frotaAccount.refresh();await poll()}catch{window.frotaAccount.user=null;window.frotaAccount.refresh()}setInterval(()=>poll(),15000);}
async function poll(){if(!window.frotaAccount.user||pollBusy||document.hidden||accountElement('accountBar').classList.contains('hidden'))return;pollBusy=true;try{
 const result=await accountApi('requests');accountElement('accountGreeting').textContent='Olá, '+window.frotaAccount.user.name;
 accountElement('myRequests').innerHTML=result.items.length?result.items.map(x=>`<div class="my-request"><strong>${safeText(x.vehicle)}${x.allDay?' · Dia inteiro':''} · ${safeText(x.date.split('-').reverse().join('/'))}${x.returnDate&&x.returnDate!==x.date?' a '+safeText(x.returnDate.split('-').reverse().join('/')):''}</strong><span class="status">${safeText(x.status==='Agendada'?'Aprovada':x.status)}</span><small>${safeText(x.id)}</small></div>`).join(''):'<p class="muted">Você ainda não enviou solicitações.</p>';
 if(!accountElement('statusDialog').open){const notices=await accountApi('notifications');if(notices.items.length){pendingNotices=notices.items;accountElement('statusMessages').innerHTML=pendingNotices.map(x=>`<p><strong>${safeText(x.status)}</strong> · ${safeText(x.vehicle)} · ${safeText(x.date.split('-').reverse().join('/'))}<br><small>${safeText(x.request_id)}</small></p>`).join('');accountElement('notificationError').textContent='';accountElement('statusDialog').showModal();}}
 }catch(error){if(error.status===401){window.frotaAccount.user=null;accountElement('statusDialog').close();window.frotaAccount.refresh()}else accountElement('myRequests').textContent='Sem conexão. Tentaremos atualizar novamente.';}finally{pollBusy=false}}
accountElement('accountSwitch').onclick=()=>{registration=!registration;accountElement('registrationName').classList.toggle('hidden',!registration);accountElement('accountName').required=registration;accountElement('accountPassword').minLength=registration?8:1;accountElement('accountPassword').autocomplete=registration?'new-password':'current-password';accountElement('accountSubmit').textContent=registration?'Criar conta e entrar':'Entrar';accountElement('accountSwitch').textContent=registration?'Já tenho uma conta':'Criar minha conta';accountElement('accountError').textContent='';};
accountElement('accountForm').onsubmit=async e=>{e.preventDefault();const button=accountElement('accountSubmit');button.disabled=true;try{const result=await accountApi(registration?'register':'login','POST',{name:accountElement('accountName').value,email:accountElement('accountEmail').value,password:accountElement('accountPassword').value});accountElement('accountPassword').value='';window.frotaAccount.user=result.user;window.frotaAccount.refresh();await poll()}catch(error){accountElement('accountError').textContent=error.message}finally{button.disabled=false}};
accountElement('accountLogout').onclick=async()=>{try{await accountApi('logout','POST',{});window.frotaAccount.user=null;accountElement('statusDialog').close();accountElement('myRequests').textContent='';window.frotaAccount.refresh()}catch(error){accountElement('myRequests').textContent=error.message}};
accountElement('statusDialog').addEventListener('cancel',e=>e.preventDefault());
accountElement('statusConfirm').onclick=async()=>{const button=accountElement('statusConfirm');button.disabled=true;try{await accountApi('notifications/seen','POST',{ids:pendingNotices.map(x=>x.id)});pendingNotices=[];accountElement('statusDialog').close();await poll()}catch(error){accountElement('notificationError').textContent=error.message}finally{button.disabled=false}};
document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll()});
