'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let admin=false,items=[],tab='pending',offline=false,syncing=false;
const desktop=!!window.frota;
const todayISO=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date());
const day=s=>s?s.split('-').reverse().join('/'):'Sem data';
const shift=(s,n)=>{const d=new Date(s+'T12:00:00');d.setDate(d.getDate()+n);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const monday=s=>shift(s,-((new Date(s+'T12:00:00').getDay()+6)%7));let week=monday(todayISO());
const tripCovers=(x,date)=>x.date<=date&&(x.returnDate||x.date)>=date;
const wholeDayOn=(x,date)=>!!x.allDay||date>x.date&&date<(x.returnDate||x.date);
const tripTime=(x,date)=>wholeDayOn(x,date)?'DIA INTEIRO':(x.returnDate||x.date)===x.date?(x.start||'a confirmar')+' – '+(x.end||'a confirmar'):date===x.date?'Retirada '+(x.start||'a confirmar'):'Devolução '+(x.end||'a confirmar');
const active=x=>!['Solicitada','Recusada','Cancelada','Concluída'].includes(x.status);
const status=x=>x.status==='Agendada'?(!x.driverConfirmed?'Aguardando motorista':x.material==='yes'&&!x.nf?'Aguardando NF':x.material==='yes'&&!x.loaded?'Aguardando carregamento':'Pronta para liberar'):x.status;
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden')}
async function api(path,method='GET',data){let result;if(desktop)result=await window.frota.api(path,method,data);else{const response=await fetch(path,{method,credentials:'same-origin',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(20000)});result={status:response.status,data:await response.json()};}if(result.status>=400){const error=new Error(result.data.error||'Falha na conexão.');Object.assign(error,result.data,{httpStatus:result.status});throw error}return result.data;}
async function mutation(path,method,d){if(offline)throw new Error('Sem conexão: alterações ficam bloqueadas para evitar conflitos.');try{return await api(path,method,d)}catch(error){if(error.confirmBoth&&confirm(error.error+'\n'+(error.other||[]).map(x=>x.vehicle+' · '+x.start+' · '+x.driver).join('\n')))return api(path,method,{...d,confirmBoth:true});throw error}}
function mode(){$('accountLogout').classList.toggle('hidden',admin||desktop||!window.frotaAccount.user);document.body.classList.toggle('desktop',desktop);$('publicView').classList.toggle('hidden',admin||desktop);$('accountGate').classList.toggle('hidden',admin||desktop||!!window.frotaAccount.user);$('accountBar').classList.toggle('hidden',admin||desktop||!window.frotaAccount.user);if(!admin&&window.frotaAccount.user){$('name').value=window.frotaAccount.user.name;$('email').value=window.frotaAccount.user.email;$('name').readOnly=true;$('email').readOnly=true}else{$('name').readOnly=false;$('email').readOnly=false}$('adminView').classList.toggle('hidden',!admin);$('contactFields').classList.toggle('hidden',admin);$('beneficiaryFields').classList.toggle('hidden',!admin);$('beneficiaryName').required=admin;if(admin&&$('beneficiaryMode').value==='self'){$('beneficiaryName').value='Administrador';$('beneficiaryName').readOnly=true;$('beneficiaryUserId').value='';}for(const id of ['beneficiaryName','beneficiaryUserId'])$(id).disabled=!admin;$('beneficiaryUserId').disabled=!admin||$('beneficiaryMode').value==='self';for(const id of ['name','department','email'])$(id).required=!admin;$('driver').required=admin;$('formTitle').textContent=admin?'Programar viagem':'Solicitar uma data';$('submitRequest').textContent=admin?'Salvar programação':'Enviar solicitação';$('formCard').classList.toggle('public-form',!admin);$('formCard').classList.toggle('hidden',!admin&&!window.frotaAccount.user);if(!admin&&!desktop&&!window.frotaAccount.user)$('formHome').appendChild($('accountGate'));(admin?$('adminFormHome'):$('formHome')).appendChild($('formCard'));$('adminToggle').textContent=admin?'Sair da administração':'Área administrativa';$('date').min=admin?'':todayISO();driverChoice();tripPeriod();publicRequestFields();}
function weeks(){const choices=new Set([week,...items.filter(x=>x.date).flatMap(x=>[monday(x.date),monday(x.returnDate||x.date)])]);for(let n=-12;n<=52;n++)choices.add(shift(monday(todayISO()),n*7));$('weekSelect').innerHTML='';for(const s of [...choices].sort())$('weekSelect').add(new Option(day(s)+' a '+day(shift(s,6)),s));$('weekSelect').value=week;}
function render(){mode();if(!admin){if(!desktop)publicCalendar();return}weeks();const weekdays=['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],weekRows=items.filter(x=>x.date<=shift(week,6)&&(x.returnDate||x.date)>=week);const metrics=[['Solicitações pendentes',items.filter(x=>x.status==='Solicitada').length],['Viagens na semana',weekRows.filter(active).length],['Motorista a confirmar',weekRows.filter(x=>active(x)&&!x.driverConfirmed).length],['NF / carga / revisão',weekRows.filter(x=>active(x)&&(x.material==='unknown'||x.material==='yes'&&(!x.nf||!x.loaded))).length]];$('summary').innerHTML=metrics.map(([label,value])=>`<div class="card"><b>${value}</b><span>${label}</span></div>`).join('');
const heads=weekdays.map((label,i)=>`<div class="day-head ${shift(week,i)===todayISO()?'today':''}">${label}<b>${day(shift(week,i))}</b></div>`).join('');
$('agenda').innerHTML='<div class="calendar-wrap"><div class="calendar"><div class="day-head">Veículo</div>'+heads+['Iveco','Saveiro'].map(vehicle=>`<div class="vehicle-label"><img class="vehicle-photo" src="/assets/${vehicle.toLowerCase()}.png" alt="Imagem ilustrativa da ${vehicle}" width="76" height="55">${vehicle}<small>${vehicle==='Iveco'?'Transporte':'Utilitário'}</small></div>${weekdays.map((_,i)=>{const date=shift(week,i),trips=weekRows.filter(x=>tripCovers(x,date)&&x.vehicle===vehicle&&!['Solicitada','Recusada','Cancelada'].includes(x.status));const fullDay=trips.some(x=>wholeDayOn(x,date)&&active(x));return `<div data-drop-date="${date}" data-drop-vehicle="${esc(vehicle)}" class="calendar-cell ${fullDay?'all-day-cell':''}"><span class="help">${trips.length?trips.length+' registro(s)':'Sem programação'}</span>${trips.map(x=>`<article data-trip-id="${esc(x.id)}" data-trip-day="${date}" class="entry ${wholeDayOn(x,date)?'all-day-entry':''}" tabindex="0" title="${esc(x.purpose)} — ${esc(x.destination)}">${!offline&&['Importada','Agendada','Liberada'].includes(x.status)?'<button type="button" class="move-trip secondary" aria-label="Segure e arraste para mudar o dia">⠿ Mover viagem</button>':''}<b>${esc(tripTime(x,date))}</b><p>${esc(x.purpose)}</p><p>${esc(x.destination)}</p>${x.name?'<p>Reserva: '+esc(x.name)+'</p>':''}<span class="status ${x.status==='Importada'?'pending':''}">${esc(status(x))}</span><small class="driver-caption">${esc(x.driver||'Motorista a definir')}</small><p>${esc(x.driver||'A definir')} · ${x.returnDate&&x.returnDate!==x.date?'Devolução '+day(x.returnDate)+' '+esc(x.end||'a confirmar'):x.allDay?'Uso durante todo o dia':'Retorno '+esc(x.end||'a confirmar')}</p><button class="secondary" data-edit="${esc(x.id)}" ${offline?'disabled':''}>Abrir viagem</button>${x.status!=='Em viagem'?`<button class="danger" data-action="delete" data-id="${esc(x.id)}" ${offline?'disabled':''}>Excluir programação</button>`:''}</article>`).join('')}<button class="secondary" data-date="${date}" data-vehicle="${vehicle}" ${offline||fullDay?'disabled':''}>${fullDay?'Dia reservado':'Programar'}</button></div>`}).join('')}`).join('')+'</div></div>';
const filtered=items.filter(x=>tab==='pending'?x.status==='Solicitada':tab==='week'?x.date<=shift(week,6)&&(x.returnDate||x.date)>=week:tab==='review'?x.status==='Importada':true);
$('requests').innerHTML=filtered.length?filtered.map(x=>`<article class="entry"><div class="top"><b>${esc(x.protocol||x.id)}</b><span class="status ${['Solicitada','Importada'].includes(x.status)?'pending':''}">${esc(status(x))}</span></div>${x.urgency==='urgent'?`<p class="error"><strong>URGENTE</strong> · ${esc(x.urgencyReason)}</p>`:''}<h4>${esc(x.vehicle)} · ${day(x.date)}${x.returnDate&&x.returnDate!==x.date?' a '+day(x.returnDate):''} · ${x.allDay?'Dia inteiro':esc(x.start||'Saída pendente')+' – '+esc(x.end||'Retorno pendente')}</h4>${x.name?`<p class="request-contact">${esc(x.name)} · ${esc(x.department||'Setor não informado')} · ${esc(x.email||'E-mail não informado')}</p>`:''}<p>${esc(x.destination)}</p><p>${esc(x.purpose)}</p><p>Motorista: ${esc(x.driver||'A definir')} · Material para obra: ${x.material==='yes'?'Sim':x.material==='no'?'Não':'A confirmar'}</p>${x.dualConfirmed?'<p>Uso dos dois carros confirmado em '+esc(x.dualConfirmed)+'.</p>':''}${x.warnings?.length?'<p>'+esc(x.warnings.join(' · '))+'</p>':''}<div class="actions">${buttons(x)}</div></article>`).join(''):'<div class="empty">Nenhum registro nesta seleção.</div>';
for(const [id,value] of [['tabPending','pending'],['tabWeek','week'],['tabReview','review'],['tabAll','all']])$(id).classList.toggle('selected',tab===value);$('connection').textContent=offline?'Sem conexão · consultando a última cópia local. Alterações bloqueadas.':'Conectado · web e aplicativo usam a mesma base.';$('connection').classList.toggle('offline',offline);}
function buttons(x){const button=(action,label,danger=false)=>`<button data-action="${action}" data-id="${esc(x.id)}" class="${danger?'danger':'secondary'}" ${offline?'disabled':''}>${label}</button>`;let result='';if(['Solicitada','Importada','Agendada','Liberada'].includes(x.status))result+=button('edit',x.status==='Solicitada'?'Analisar e aprovar':'Editar programação');if(x.status==='Solicitada')result+=button('reject','Recusar',true);if(x.status==='Agendada'){result+=button('driver',x.driverConfirmed?'Desmarcar motorista':'Motorista confirmou');if(x.material==='yes')result+=button('nf',x.nf?'Desmarcar NF':'NF conferida')+button('load',x.loaded?'Desmarcar carga':'Carga confirmada');result+=button('release','Liberar saída')}if(x.status==='Liberada')result+=button('depart','Registrar saída');if(x.status==='Em viagem')result+=button('finish','Registrar retorno');if(['Solicitada','Importada','Agendada','Liberada'].includes(x.status))result+=button('cancel','Cancelar',true);if(x.status!=='Em viagem')result+=button('delete','Excluir programação',true);return result;}
async function sync(notify=false){if(!admin||syncing)return;syncing=true;try{const old=new Set(items.map(x=>x.id)),data=await api('/api/requests');items=data.items;offline=!!data.offline;if(notify&&!offline){const fresh=items.filter(x=>x.status==='Solicitada'&&!old.has(x.id));if(fresh.length){toast(fresh.length+' nova(s) solicitação(ões) recebida(s).');if(desktop)await window.frota.notify(fresh.length);}}render()}catch(error){if(error.httpStatus===401){admin=false;items=[];mode();toast('Sessão expirada. Entre novamente.')}else toast(error.message)}finally{syncing=false}}
function purpose(){const selected=$('purpose').value,material=selected.includes('material'),other=selected==='Outro serviço',delivery=selected==='Levar material para obra';$('detailsGroup').classList.toggle('hidden',!material&&!other);$('details').required=material||other;$('detailsLabel').textContent=other?'Descreva o serviço *':'Material e quantidade *';$('materialGroup').classList.toggle('hidden',delivery||!selected);$('material').required=!!selected&&!delivery;$('material').value=delivery?'yes':'';$('requestHint').textContent=delivery?'Entrega em obra: NF e carga serão obrigatórias antes da saída.':admin?'Programações do Motorista padrão nos dois veículos no mesmo dia exigem confirmação.':'Motorista e horários serão definidos pela administração.';}
$('purpose').onchange=purpose;
function driverChoice(){const choice=$('driverMode').value;$('driverField').classList.remove('hidden');$('driver').readOnly=choice!=='other';$('driver').required=true;if(choice==='fleet')$('driver').value='Motorista padrão';if(choice==='self')$('driver').value=admin?'Administrador':window.frotaAccount.user?.name||'';}
function tripPeriod(editing=false){const whole=$(editing?'editAllDay':'allDay').value==='true';$(editing?'editTimes':'tripTimes').classList.toggle('hidden',whole);for(const name of editing?['editStart','editEnd']:['start','end']){$(name).disabled=whole;$(name).required=!whole}if(!editing)$('allDayHint').classList.toggle('hidden',!whole);}
$('driverMode').onchange=()=>{if($('driverMode').value==='other')$('driver').value='';driverChoice()};$('allDay').onchange=()=>tripPeriod();$('editAllDay').onchange=()=>tripPeriod(true);
$('date').onchange=()=>{$('returnDate').min=$('date').value;if(!$('returnDate').value||$('returnDate').value<$('date').value)$('returnDate').value=$('date').value};$('editDate').onchange=()=>{$('editReturnDate').min=$('editDate').value;if($('editReturnDate').value<$('editDate').value)$('editReturnDate').value=$('editDate').value};
$('beneficiaryMode').onchange=async()=>{const other=$('beneficiaryMode').value==='other';$('beneficiaryName').readOnly=!other;$('beneficiaryName').value=other?'':'Administrador';$('beneficiaryUserId').value='';$('beneficiaryUserId').disabled=!other;if(other){try{const rows=(await api('/api/users')).users;$('beneficiaryUserId').innerHTML='<option value="">Digitar nome / sem conta vinculada</option>'+rows.map(u=>`<option value="${esc(u.id)}" data-name="${esc(u.name)}">${esc(u.name)} · ${esc(u.email)}</option>`).join('')}catch(error){toast(error.message)}}};
$('beneficiaryUserId').onchange=()=>{const selected=$('beneficiaryUserId').selectedOptions[0];$('beneficiaryName').readOnly=!!$('beneficiaryUserId').value;if(selected?.dataset.name)$('beneficiaryName').value=selected.dataset.name};
$('requestForm').onsubmit=async e=>{e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f));if(d.allDay==='true'){d.start='00:00';d.end='23:59'}if(admin&&(!d.returnDate||d.returnDate===d.date)&&d.end<=d.start){$('formMessage').textContent='O retorno deve ser posterior à saída.';return}if(d.details?.trim())d.purpose+=' — '+d.details.trim();if(!admin&&!d.returnDate)d.returnDate=d.date;$('submitRequest').disabled=true;try{const result=await mutation(admin?'/api/trips':'/api/requests','POST',d);f.reset();purpose();driverChoice();tripPeriod();$('formMessage').textContent=admin?'Programação salva. Confira motorista, NF e carga.':'Pedido recebido! Protocolo: '+result.id+'. Aguarde a aprovação.';if(admin){week=monday(d.date);await sync()}else{mode();await window.frotaAccount.poll()}}catch(error){$('formMessage').textContent=error.message}finally{$('submitRequest').disabled=false}};
$('adminToggle').onclick=async()=>{if(admin){try{await api('/api/logout','POST',{})}catch{}admin=false;items=[];offline=false;render();return}$('loginError').textContent='';$('loginDialog').showModal()};$('closeLogin').onclick=()=>$('loginDialog').close();
$('loginForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button[type="submit"]');b.disabled=true;try{await api('/api/login','POST',{password:$('adminPassword').value});$('adminPassword').value='';admin=true;$('loginDialog').close();await sync()}catch(error){$('loginError').textContent=error.message}finally{b.disabled=false}};
function edit(id){const x=items.find(x=>x.id===id);if(!x)return;if(!['Solicitada','Importada','Agendada','Liberada'].includes(x.status)){toast('Esta viagem não pode ser editada nesta etapa.');return}const f=$('editForm');for(const name of ['id','date','returnDate','start','end','vehicle','destination','purpose','material','driver'])f.elements[name].value=x[name]||'';f.elements.returnDate.value=x.returnDate||x.date;f.elements.allDay.value=x.allDay?'true':'false';tripPeriod(true);if(x.material==='unknown')f.elements.material.value='';if(!x.driver)f.elements.driver.value='Motorista padrão';$('editMessage').textContent=x.urgency==='urgent'?'URGENTE: '+x.urgencyReason:'';$('editDialog').showModal()}
$('closeEdit').onclick=()=>$('editDialog').close();$('editForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),x=items.find(x=>x.id===d.id),b=e.target.querySelector('button[type="submit"]');b.disabled=true;try{await mutation('/api/requests/'+encodeURIComponent(d.id),'PATCH',{...d,version:x.version,action:x.status==='Solicitada'?'approve':'edit'});$('editDialog').close();await sync()}catch(error){$('editMessage').textContent=error.message}finally{b.disabled=false}};
$('requests').onclick=async e=>{const b=e.target.closest('button[data-action]');if(!b||!admin||offline)return;const x=items.find(x=>x.id===b.dataset.id);if(b.dataset.action==='edit'){edit(x.id);return}if(['cancel','reject','delete'].includes(b.dataset.action)&&!confirm('Confirma '+(b.dataset.action==='delete'?'excluir a programação do painel':b.dataset.action==='cancel'?'cancelar':'recusar')+' este registro?'))return;b.disabled=true;try{await mutation('/api/requests/'+encodeURIComponent(x.id),'PATCH',{action:b.dataset.action,version:x.version});await sync()}catch(error){toast(error.message);b.disabled=false}};
$('agenda').onclick=async e=>{if(e.target.closest('button[data-action="delete"]')){await $('requests').onclick(e);return}const editButton=e.target.closest('button[data-edit]');if(editButton){edit(editButton.dataset.edit);return}const b=e.target.closest('button[data-date]');if(!b)return;if(!window.frotaAccount.user){toast('Entre ou crie sua conta para solicitar uma viagem.');$('accountGate').scrollIntoView({behavior:'smooth',block:'start'});$('accountEmail').focus({preventScroll:true});return}$('date').value=b.dataset.date;$('returnDate').value=b.dataset.date;$('returnDate').min=b.dataset.date;$('vehicle').value=b.dataset.vehicle;$('requestForm').scrollIntoView({behavior:'smooth',block:'start'})};
function selectWeek(value){week=monday(value);render()};$('weekSelect').onchange=()=>selectWeek($('weekSelect').value);$('prevWeek').onclick=()=>selectWeek(shift(week,-7));$('nextWeek').onclick=()=>selectWeek(shift(week,7));$('currentWeek').onclick=()=>selectWeek(todayISO());$('refresh').onclick=()=>sync();for(const [id,value] of [['tabPending','pending'],['tabWeek','week'],['tabReview','review'],['tabAll','all']])$(id).onclick=()=>{tab=value;render()};
$('backup').onclick=()=>{if(admin)downloadBlob(new Blob([JSON.stringify(items,null,2)],{type:'application/json'}),'frota-backup-'+todayISO()+'.json')};
$('importLegacy').onclick=async()=>{if(!admin||offline)return;let data;try{if(desktop)data=await window.frota.seed();else{const raw=localStorage.getItem('frota-beta-v1');if(raw)data=JSON.parse(raw)}}catch{}if(!data){$('backupFile').click();return}await importRecords(data)};
async function importRecords(data){try{if(!Array.isArray(data))throw new Error('Arquivo inválido.');const excel=data.filter(x=>x.id?.startsWith('EXCEL-')&&typeof x.vehicle==='string');if(!excel.length)throw new Error('Nenhum registro de Excel encontrado.');if(!confirm('Importar '+excel.length+' registros do Excel para a base online?'))return;const result=await mutation('/api/import','POST',excel);toast(result.imported+' registros importados. Registros existentes foram preservados.');await sync()}catch(error){toast(error.message)}}
$('backupFile').onchange=async e=>{try{if(e.target.files[0])await importRecords(JSON.parse(await e.target.files[0].text()))}catch{toast('Não foi possível ler o arquivo JSON.')}e.target.value=''};
$('exportPDF').onclick=async()=>{if(!admin)return;const html=weeklyPrintHTML(items,week,document.querySelector('.brand-logo').src);if(desktop){try{await window.frota.pdf(html,'programacao-'+week+'.pdf')}catch(e){toast(e.message)}return}const popup=window.open('','_blank');if(!popup){toast('Permita abrir a janela para exportar o PDF.');return}popup.document.write(html);popup.document.close();popup.onload=()=>{popup.focus();popup.print()};};
$('configButton').onclick=async()=>{const config=await window.frota.config();$('apiUrl').value=config.apiUrl||'';$('configDialog').showModal()};$('closeConfig').onclick=()=>$('configDialog').close();$('configForm').onsubmit=async e=>{e.preventDefault();try{await window.frota.configure($('apiUrl').value);admin=false;items=[];$('configDialog').close();mode();$('loginDialog').showModal()}catch(error){$('configError').textContent=error.message}};
async function init(){mode();purpose();if(desktop){const config=await window.frota.config();if(!config.apiUrl){$('configDialog').showModal();return}}try{await api('/api/me');admin=true;await sync()}catch{if(desktop)$('loginDialog').showModal();}if(!desktop)await window.frotaAccount.init();setInterval(()=>sync(true),30000)}
let publicWeek=monday(todayISO()),calendarGeneration=0;
async function publicCalendar(){
 const generation=++calendarGeneration,start=publicWeek;$('publicWeek').value=start;
 $('publicAgenda').textContent='Consultando programação…';
 try{const data=await api('/api/calendar?week='+start);if(generation!==calendarGeneration)return;
 const days=['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'];
 $('publicAgenda').innerHTML=`<div class="calendar-wrap"><table class="request-calendar"><thead><tr><th scope="col">Veículo</th>${days.map((label,i)=>`<th scope="col" class="${shift(start,i)===todayISO()?'today':''}">${label}<b>${day(shift(start,i))}</b></th>`).join('')}</tr></thead><tbody>${['Iveco','Saveiro'].map(vehicle=>`<tr><th scope="row"><img class="vehicle-photo" src="/assets/${vehicle.toLowerCase()}.png" alt="Imagem ilustrativa da ${vehicle}" width="76" height="55">${vehicle}</th>${days.map((_,i)=>{const date=shift(start,i),trips=data.items.filter(x=>tripCovers(x,date)&&x.vehicle===vehicle),past=date<todayISO(),fullDay=trips.some(x=>wholeDayOn(x,date)&&x.status!=='Concluída');return `<td class="${fullDay?'all-day-cell':''} ${$('date').value===date&&$('vehicle').value===vehicle?'chosen':''}">${trips.length?trips.map(x=>`<div class="calendar-slot ${x.allDay?'all-day-entry':''}"><b>${esc(tripTime(x,date))}</b>${x.urgency==='urgent'?'<strong class="urgent-badge">URGENTE</strong>':''}<span class="calendar-destination">${esc(x.destination||'Destino a confirmar')}</span><span>${esc(x.status)}</span></div>`).join(''):'<span class="help">Sem programação</span>'}<button class="secondary" data-date="${date}" data-vehicle="${vehicle}" ${past||fullDay?'disabled':''}>${past?'Data passada':fullDay?'Dia reservado':'Solicitar este dia'}</button></td>`}).join('')}</tr>`).join('')}</tbody></table></div>`;
 }catch(error){if(generation===calendarGeneration)$('publicAgenda').textContent='Não foi possível consultar a agenda. Você pode preencher o pedido ao lado. '+error.message;}
}
$('publicPrev').onclick=()=>{publicWeek=shift(publicWeek,-7);publicCalendar()};$('publicNext').onclick=()=>{publicWeek=shift(publicWeek,7);publicCalendar()};$('publicCurrent').onclick=()=>{publicWeek=monday(todayISO());publicCalendar()};$('publicWeek').onchange=()=>{if($('publicWeek').value){publicWeek=monday($('publicWeek').value);publicCalendar()}};
$('publicAgenda').onclick=e=>{const b=e.target.closest('button[data-date]');if(!b)return;$('date').value=b.dataset.date;$('vehicle').value=b.dataset.vehicle;publicCalendar();$('formMessage').textContent='Selecionado: '+b.dataset.vehicle+' · '+day(b.dataset.date)+'. Informe seu setor, finalidade e destino.';$('requestForm').scrollIntoView({behavior:'smooth',block:'start'});$('name').focus({preventScroll:true})};
let registeredUsers=[],resetUserId='';
function adminPanel(panel){if(!admin)return;for(const key of ['planning','logins']){const selected=key===panel;$(key+'Panel').classList.toggle('hidden',!selected);$(key+'Tab').classList.toggle('selected',selected);$(key+'Tab').setAttribute('aria-selected',String(selected));$(key+'Tab').tabIndex=selected?0:-1;}if(panel==='logins')$('loadUsers').click();}
$('planningTab').onclick=()=>adminPanel('planning');$('loginsTab').onclick=()=>adminPanel('logins');
for(const id of ['planningTab','loginsTab'])$(id).onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const panel=e.key==='Home'?'planning':e.key==='End'?'logins':id==='planningTab'?'logins':'planning';adminPanel(panel);$(panel+'Tab').focus()}};
$('loadUsers').onclick=async()=>{if(!admin)return;$('loadUsers').disabled=true;try{registeredUsers=(await api('/api/users')).users;$('usersList').innerHTML=registeredUsers.length?registeredUsers.map(u=>`<article class="entry"><strong>${esc(u.name)}</strong><p>${esc(u.email)}</p><p class="help">Cadastro: ${esc(new Date(u.created_at).toLocaleDateString('pt-BR'))}</p><button class="secondary" data-reset-user="${esc(u.id)}" ${offline?'disabled':''}>Redefinir / mudar senha</button><button class="danger" data-delete-user="${esc(u.id)}" ${offline?'disabled':''}>Excluir login</button></article>`).join(''):'<p>Nenhuma conta cadastrada.</p>'}catch(error){$('usersList').textContent=error.message}finally{$('loadUsers').disabled=false}};
$('usersList').onclick=async e=>{const remove=e.target.closest('button[data-delete-user]');if(remove&&admin&&!offline){const user=registeredUsers.find(u=>u.id===remove.dataset.deleteUser);if(!user||!confirm('Excluir o login de '+user.name+'?\nO acesso será encerrado. As viagens serão preservadas e o e-mail ficará reservado.'))return;remove.disabled=true;try{await mutation('/api/users/'+encodeURIComponent(user.id),'PATCH',{action:'delete'});$('loadUsers').click();toast('Login excluído e sessões encerradas.')}catch(error){toast(error.message);remove.disabled=false}return;}const b=e.target.closest('button[data-reset-user]');if(!b||!admin||offline)return;const user=registeredUsers.find(u=>u.id===b.dataset.resetUser);if(!user)return;resetUserId=user.id;$('resetAccountName').textContent=user.name+' · '+user.email;$('resetPasswordForm').reset();$('resetPasswordError').textContent='';$('resetPasswordDialog').showModal()};
$('closeResetPassword').onclick=()=>{$('resetPasswordForm').reset();$('resetPasswordDialog').close()};
$('resetPasswordForm').onsubmit=async e=>{e.preventDefault();if($('resetPassword').value!==$('resetPasswordConfirm').value){$('resetPasswordError').textContent='As senhas devem ser iguais.';return}const button=e.target.querySelector('button[type="submit"]');button.disabled=true;try{await mutation('/api/users/'+encodeURIComponent(resetUserId),'PATCH',{password:$('resetPassword').value});e.target.reset();$('resetPasswordDialog').close();toast('Senha atualizada. A pessoa deve entrar novamente com a nova senha.')}catch(error){$('resetPasswordError').textContent=error.message}finally{button.disabled=false}};
window.frotaAccount.refresh=()=>render();init();
// A dedicated handle keeps normal touch scrolling available on the cards.
let tripDrag=null,movingTrip=false;
function clearTripDrag(){if(!tripDrag)return;clearTimeout(tripDrag.timer);tripDrag.card.classList.remove('dragging-trip');document.querySelectorAll('.drop-target').forEach(el=>el.classList.remove('drop-target'));tripDrag=null;}
function dragTarget(event){const cell=document.elementFromPoint(event.clientX,event.clientY)?.closest('[data-drop-date]');return cell?.dataset.dropVehicle===tripDrag.vehicle?cell:null;}
$('agenda').addEventListener('pointerdown',event=>{const handle=event.target.closest('.move-trip');if(!handle||!admin||offline||movingTrip||event.button!==0)return;const card=handle.closest('[data-trip-id]'),trip=items.find(x=>x.id===card.dataset.tripId);if(!trip)return;event.preventDefault();handle.setPointerCapture(event.pointerId);tripDrag={card,handle,id:trip.id,vehicle:trip.vehicle,from:card.dataset.tripDay,x:event.clientX,y:event.clientY,pointer:event.pointerId,ready:true,target:null};if(tripDrag.ready)card.classList.add('dragging-trip');else tripDrag.timer=setTimeout(()=>{if(tripDrag){tripDrag.ready=true;card.classList.add('dragging-trip')}},350);});
$('agenda').addEventListener('pointermove',event=>{if(!tripDrag||tripDrag.pointer!==event.pointerId)return;if(!tripDrag.ready){if(Math.hypot(event.clientX-tripDrag.x,event.clientY-tripDrag.y)>12)clearTripDrag();return}event.preventDefault();const wrap=tripDrag.card.closest('.calendar-wrap'),rect=wrap.getBoundingClientRect();if(event.clientX<rect.left+40)wrap.scrollLeft-=16;else if(event.clientX>rect.right-40)wrap.scrollLeft+=16;tripDrag.target=dragTarget(event);document.querySelectorAll('.drop-target').forEach(el=>el.classList.remove('drop-target'));tripDrag.target?.classList.add('drop-target');});
$('agenda').addEventListener('pointerup',event=>{if(!tripDrag||tripDrag.pointer!==event.pointerId)return;const drag=tripDrag,target=drag.ready?dragTarget(event):null;clearTripDrag();if(target&&target.dataset.dropDate!==drag.from)moveTrip(drag.id,drag.from,target.dataset.dropDate);});
$('agenda').addEventListener('pointercancel',clearTripDrag);
$('agenda').addEventListener('lostpointercapture',clearTripDrag);
$('agenda').addEventListener('click',event=>{if(event.target.closest('.move-trip'))event.preventDefault();});
async function moveTrip(id,from,to){const trip=items.find(x=>x.id===id);if(!trip||!admin||offline||movingTrip)return;const offset=Math.round((Date.parse(to+'T12:00:00Z')-Date.parse(from+'T12:00:00Z'))/86400000),date=shift(trip.date,offset),returnDate=shift(trip.returnDate||trip.date,offset);if(!trip.start||!trip.end||!['yes','no'].includes(trip.material)||!trip.driver){edit(id);$('editMessage').textContent='Complete os dados da viagem antes de mudar a data.';return}if(!confirm('Mover '+trip.vehicle+' de '+day(trip.date)+' para '+day(date)+(returnDate!==date?' até '+day(returnDate):'')+'?\nOs horários e a duração serão mantidos. Motorista, NF e carga precisarão ser reconfirmados.'))return;movingTrip=true;try{await mutation('/api/requests/'+encodeURIComponent(id),'PATCH',{...trip,date,returnDate,action:'edit',version:trip.version});week=monday(to);await sync();toast('Viagem movida. Confira motorista, NF e carga.')}catch(error){toast('Não foi possível mover: '+error.message);await sync()}finally{movingTrip=false}}
function whatsappPreview(){if(!admin)return;const daily=$('whatsappPeriod').value==='day',start=daily?$('whatsappDate').value:week,end=daily?start:shift(week,6);$('whatsappDate').disabled=!daily;$('whatsappMessage').textContent='';if(!start){$('whatsappText').value='Escolha o dia.';$('copyWhatsapp').disabled=true;return}const driverName=value=>String(value||'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const trips=items.filter(x=>driverName(x.driver)==='motorista padrao'&&['Agendada','Liberada','Em viagem'].includes(x.status)&&x.date<=end&&(x.returnDate||x.date)>=start).sort((a,b)=>a.date.localeCompare(b.date)||String(a.start||'').localeCompare(String(b.start||'')));const lines=['*Frota Modelo · Motorista padrão*',daily?'*Programação do dia '+day(start)+'*':'*Semana '+day(start)+' a '+day(end)+'*'];if(offline)lines.push('⚠ Cópia offline: confira a programação online antes de sair.');for(let date=start;date<=end;date=shift(date,1)){const scheduled=trips.filter(x=>tripCovers(x,date));if(!scheduled.length)continue;lines.push('','*'+new Intl.DateTimeFormat('pt-BR',{weekday:'long'}).format(new Date(date+'T12:00:00'))+' · '+day(date)+'*');for(const x of scheduled){lines.push('• *'+x.vehicle+' · '+tripTime(x,date)+'*',x.purpose,'Destino: '+x.destination);if((x.returnDate||x.date)!==x.date)lines.push('Reserva: '+day(x.date)+' a '+day(x.returnDate)+(x.allDay?' · dia inteiro':' · devolução às '+x.end));const pending=[];if(!x.driverConfirmed)pending.push('confirmar motorista');if(x.material==='yes'){if(!x.nf)pending.push('conferir NF');if(!x.loaded)pending.push('confirmar carga');}if(pending.length)lines.push('⚠ Antes da saída: '+pending.join(', ')+'.');if(x.notes)lines.push('Observação: '+x.notes);lines.push('');}}if(!trips.length)lines.push('','Nenhuma viagem programada para você neste período.');else lines.push('Confira a programação atual e as pendências antes de sair.');$('whatsappText').value=lines.join('\n');$('copyWhatsapp').disabled=false;}
$('whatsappSummary').onclick=async()=>{if(!admin)return;await sync();if(!admin)return;$('whatsappPeriod').value='day';$('whatsappDate').value=todayISO();whatsappPreview();$('whatsappDialog').showModal()};
$('whatsappPeriod').onchange=whatsappPreview;$('whatsappDate').onchange=whatsappPreview;
$('closeWhatsapp').onclick=()=>$('whatsappDialog').close();
$('copyWhatsapp').onclick=async()=>{if(!admin)return;try{await navigator.clipboard.writeText($('whatsappText').value);$('whatsappMessage').textContent='Mensagem copiada. Cole na conversa do Motorista padrão no WhatsApp.'}catch{$('whatsappText').focus();$('whatsappText').select();$('whatsappMessage').textContent='Selecione e copie a mensagem para colar no WhatsApp.'}};
function publicRequestFields(){const publicMode=!admin;$('driverChoices').classList.toggle('hidden',publicMode);$('periodChoices').classList.toggle('hidden',publicMode);$('urgencyFields').classList.toggle('hidden',!publicMode);for(const id of ['driverMode','driver','allDay','start','end'])$(id).disabled=publicMode||(['start','end'].includes(id)&&$('allDay').value==='true');$('driver').required=!publicMode;for(const id of ['start','end'])$(id).required=!publicMode&&$('allDay').value!=='true';$('returnDate').required=!publicMode;document.querySelector('label[for="date"]').textContent=publicMode?'Dia desejado *':'Retirada *';document.querySelector('label[for="returnDate"]').textContent=publicMode?'Até qual dia? (opcional)':'Data de devolução *';$('urgency').disabled=!publicMode;const urgent=publicMode&&$('urgency').value==='urgent';$('urgencyReasonGroup').classList.toggle('hidden',!urgent);$('urgencyReason').required=urgent;$('urgencyReason').disabled=!urgent;$('requestHint').textContent=publicMode?'Motorista e horários serão definidos pela administração. Urgência não garante disponibilidade.':$('requestHint').textContent;}
$('urgency').onchange=publicRequestFields;
