const {app,BrowserWindow,ipcMain,Notification,dialog,safeStorage,shell}=require('electron');
const fs=require('node:fs/promises'),path=require('node:path'),http=require('node:http');
let window,server,token='',config={apiUrl:''},cache={items:[],syncedAt:null};
const base=path.join(__dirname,'..'),dataFile=()=>path.join(app.getPath('userData'),'state.json');
async function save(){const state={config,cache};if(token){if(!safeStorage.isEncryptionAvailable())throw Error('Proteção de credenciais indisponível no Windows.');state.session=safeStorage.encryptString(token).toString('base64')}await fs.mkdir(app.getPath('userData'),{recursive:true});const file=dataFile();await fs.writeFile(file+'.tmp',JSON.stringify(state),'utf8');await fs.rename(file+'.tmp',file)}
function validURL(value){const url=new URL(value);if(url.username||url.password||url.search||url.hash||url.pathname!=='/'||!(url.protocol==='https:'||url.protocol==='http:'&&['localhost','127.0.0.1'].includes(url.hostname)))throw Error('Use a origem HTTPS da API (sem caminho).');return url.origin;}
const secureWindow=(options={})=>new BrowserWindow({...options,webPreferences:{preload:path.join(__dirname,'preload.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true}});
async function startServer(){server=http.createServer(async(req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;const allowed=['/','/index.html','/app.js','/accounts.js','/style.css','/theme.css','/design.css','/theme.js','/exportacoes.js','/assets/logo.svg','/assets/favicon.svg','/assets/iveco.png','/assets/saveiro.png'];if(!allowed.includes(pathname)){res.writeHead(404);res.end();return}try{const filename=path.join(base,'web',pathname==='/'?'index.html':pathname.slice(1));res.writeHead(200,{'Cache-Control':'no-store','Content-Type':({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'})[path.extname(filename)],'Content-Security-Policy':"default-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'self'; connect-src 'self'; base-uri 'self'; frame-ancestors 'none'"});res.end(await fs.readFile(filename))}catch{res.writeHead(404);res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));return 'http://127.0.0.1:'+server.address().port;}
function validateSender(event){if(event.sender!==window?.webContents)throw Error('Origem não permitida.')}
function register(name,fn){ipcMain.handle(name,async(event,...args)=>{validateSender(event);return fn(...args)})}
register('config',()=>({apiUrl:config.apiUrl||'',syncedAt:cache.syncedAt,theme:config.theme||'dark',version:app.getVersion()}));
register('theme',async value=>{if(!['dark','light'].includes(value))throw Error('Tema inválido.');config.theme=value;await save();return {ok:true}});
register('configure',async url=>{config.apiUrl=validURL(url);token='';cache={items:[],syncedAt:null};await save();return {ok:true}});
register('seed',async()=>JSON.parse(await fs.readFile(path.join(base,'data/seed.json'),'utf8')));
register('api',async(route,method='GET',data)=>{
 if(typeof route!=='string'||!/^\/api\/(login|logout|me|health|requests(?:\/[A-Za-z0-9-]+)?|users(?:\/[A-Za-z0-9-]+)?|trips|import)$/.test(route)||!['GET','POST','PATCH'].includes(method))throw Error('Rota inválida.');
 if(!config.apiUrl)return {status:503,data:{error:'Configure a conexão com a API.'}};
 if(route==='/api/logout'){const old=token;token='';await save();try{await fetch(config.apiUrl+route,{method:'POST',headers:{Authorization:'Bearer '+old}})}catch{}return {status:200,data:{ok:true}};}
 try{const response=await fetch(config.apiUrl+route,{method,headers:{'Content-Type':'application/json','X-Frota-Desktop':'1',...(token?{Authorization:'Bearer '+token}:{})},body:method==='GET'?undefined:JSON.stringify(data||{}),signal:AbortSignal.timeout(15000)});const result=await response.json();
 if(route==='/api/login'&&response.ok){token=result.token;delete result.token;await save();}
 if(route==='/api/requests'&&method==='GET'&&response.ok){cache={items:result.items,syncedAt:new Date().toISOString()};await save();}
 if(response.status===401){token='';await save();}return {status:response.status,data:result};
 }catch(error){if(token&&route==='/api/me'&&method==='GET')return {status:200,data:{admin:true,offline:true}};if(token&&route==='/api/requests'&&method==='GET')return {status:200,data:{...cache,offline:true}};return {status:503,data:{error:'Sem conexão com a API. '+(cache.syncedAt?'Última sincronização: '+cache.syncedAt:'Ainda não há cópia sincronizada.')}};}
});
register('notify',count=>{if(Number.isInteger(count)&&count>0&&Notification.isSupported())new Notification({title:'Frota Modelo · '+app.getVersion(),body:count+' nova(s) solicitação(ões) aguardando análise.'}).show()});
register('pdf',async(html,name)=>{if(typeof html!=='string'||html.length>3000000||typeof name!=='string')throw Error('Relatório inválido.');const {filePath,canceled}=await dialog.showSaveDialog(window,{defaultPath:name.replace(/[^a-zA-Z0-9.-]/g,'-'),filters:[{name:'PDF',extensions:['pdf']}]});if(canceled)return {saved:false};const printWindow=new BrowserWindow({show:false,webPreferences:{nodeIntegration:false,contextIsolation:true,sandbox:true,javascript:false}});try{await printWindow.loadURL('data:text/html;charset=utf-8,'+encodeURIComponent(html));const bytes=await printWindow.webContents.printToPDF({landscape:true,pageSize:'A4',printBackground:true,preferCSSPageSize:true});await fs.writeFile(filePath,bytes);return {saved:true}}finally{printWindow.destroy()}});
app.whenReady().then(async()=>{app.setAppUserModelId('br.com.empresa.frota');try{const state=JSON.parse(await fs.readFile(dataFile(),'utf8'));config=state.config||{};if(config.apiUrl)config.apiUrl=validURL(config.apiUrl);cache=state.cache||cache;if(state.session&&safeStorage.isEncryptionAvailable())token=safeStorage.decryptString(Buffer.from(state.session,'base64'))}catch{}
const origin=await startServer();window=secureWindow({width:1500,height:960,minWidth:850,minHeight:600,title:'Frota Modelo'});window.webContents.setWindowOpenHandler(({url})=>{if(url.startsWith('https://'))shell.openExternal(url);return {action:'deny'}});window.webContents.on('will-navigate',(event,url)=>{if(!url.startsWith(origin+'/'))event.preventDefault()});window.webContents.on('will-attach-webview',event=>event.preventDefault());await window.loadURL(origin);
});
app.on('window-all-closed',()=>{server?.close();app.quit()});
